--用户表  允许使用姓名,邮箱,手机号登陆
DROP TABLE IF EXISTS `STARK_USER`;
CREATE TABLE "STARK_USER" (
  "ID" bigint NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  "USER_ID" varchar(64)  NOT NULL COMMENT '业务主键(用户id)',
  "USER_NAME" varchar(18) NOT NULL UNIQUE COMMENT '用户姓名',
  "USER_EMAIL" varchar(64)  NOT NULL UNIQUE COMMENT '用户邮箱',
  "USER_PHONE" varchar(13) DEFAULT NULL COMMENT '用户手机号',
  "USER_PASSWORD" varchar(64) NOT NULL UNIQUE COMMENT '用户密码[加密]',
  "USER_SALT" varchar(64) NOT NULL COMMENT '用户密码盐',
  "USER_STATE" tinyint NOT NULL DEFAULT 0 COMMENT '用户状态:禁用1,启用0',
  "GTM_CREATE" datetime DEFAULT NULL COMMENT '创建时间',
  "GTM_UPDATE" datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY ("ID"),
  UNIQUE KEY "USER_ID_IDX" ("USER_ID")
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--角色表  
DROP TABLE IF EXISTS `STARK_ROLE`;
CREATE TABLE "STARK_USER" (
  "ID" bigint NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  "ROLE_ID" varchar(64)  NOT NULL COMMENT '业务主键(角色id)',
  "ROLE_NAME" varchar(18) NOT NULL COMMENT '用户姓名',
  "ROLE_STATE" tinyint NOT NULL DEFAULT 0 COMMENT '角色状态:禁用1,启用0',
  "GTM_CREATE" datetime DEFAULT NULL COMMENT '创建时间',
  "GTM_UPDATE" datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY ("ID"),
  UNIQUE KEY "ROLE_ID_IDX" ("ROLE_ID")
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--用户 角色关联表
DROP TABLE IF EXISTS `STARK_USER_ROLE`;
CREATE TABLE "STARK_USER" (
  "ID" bigint NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  "USER_ROLE_ID" varchar(64)  NOT NULL COMMENT '业务主键(用户角色id)',
  "USER_ID" varchar(64)  NOT NULL COMMENT '用户id',
  "ROLE_ID" varchar(64)  NOT NULL COMMENT '角色id',
  "GTM_CREATE" datetime DEFAULT NULL COMMENT '创建时间',
  "GTM_UPDATE" datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY ("ID"),
  UNIQUE KEY "USER_ROLE_ID_IDX" ("USER_ROLE_ID")
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--资源表  
DROP TABLE IF EXISTS `STARK_USER`;
CREATE TABLE "STARK_USER" (
  "ID" bigint NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  "RESOURCE_ID" varchar(64)  NOT NULL COMMENT '业务主键(资源id)',
  "RESOURCE_NAME" varchar(64)  DEFAULT NULL COMMENT '资源名称',
  "RESOURCE_TYPE" tinyint  NOT NULL DEFAULT 0 COMMENT '资源类型:菜单,按钮,超链接',
  "RESOURCE_MENU_PARENT" varchar(64) DEFAULT NULL COMMENT '菜单资源父节点',
  "RESOURCE_MENU_LEAF" tinyint NOT NULL DEFAULT 0 COMMENT '是否是叶子节点,0:是,1 不是',
  "RESOURCE_URL" varchar(255) NOT NULL COMMENT '资源访问路径',
  "RESOURCE_STATE" tinyint NOT NULL DEFAULT 0 COMMENT '资源状态:禁用1,启用0',
  "GTM_CREATE" datetime DEFAULT NULL COMMENT '创建时间',
  "GTM_UPDATE" datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY ("ID"),
  UNIQUE KEY "RESOURCE_ID_IDX" ("RESOURCE_ID")
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--资源角色关联表
DROP TABLE IF EXISTS `STARK_ROLE_RESOURCE`;
CREATE TABLE "STARK_USER" (
  "ID" bigint NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  "ROLE_RESOURCE_ID" varchar(64)  NOT NULL COMMENT '业务主键(角色资源id)',
  "ROLE_ID" varchar(64)  NOT NULL COMMENT '角色id',
  "RESOURCE_ID" varchar(64)  NOT NULL COMMENT '资源id',
  "PERMISSION" varchar(8) NOT NULL DEFAULT 0 COMMENT '权限CRUD:0000,全权限,0011,读创建,0001,读修改,1011,只读',
  "GTM_CREATE" datetime DEFAULT NULL COMMENT '创建时间',
  "GTM_UPDATE" datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY ("ID"),
  UNIQUE KEY "ROLE_RESOURCE_ID_IDX" ("ROLE_RESOURCE_ID")
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--操作日志表
DROP TABLE IF EXISTS `STARK_ACCESS_LOG`;
CREATE TABLE "STARK_ACCESS_LOG" (
  "ID" bigint NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  "ACCESS_LOG_ID" varchar(64)  NOT NULL COMMENT '业务主键(用户角色id)',
  "ACCESS_IP"  varchar(64)  NOT NULL COMMENT 'ip',
  "USER_ID" varchar(64)  NOT NULL COMMENT '用户id',
  "OPERATE_TYPE" tinyint NOT NULL DEFAULT 0 COMMENT '操作类型:查询0,创建1,修改2,删除3',
  "OPERATE_REQ" varchar(255) NOT NULL COMMENT '操作参数json',
  "OPERATOR_NOTE" varchar(255) DEFAULT NULL '备注,失败原因',
  "GTM_CREATE" datetime DEFAULT NULL COMMENT '创建时间',
  "GTM_UPDATE" datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY ("ID"),
  UNIQUE KEY "ACCESS_LOG_ID_IDX" ("ACCESS_LOG_ID")
) ENGINE=InnoDB DEFAULT CHARSET=utf8;